name: Control Datadog-agent on Linux servers

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to control (e.g., datadog-agent)'
        required: true
        default: 'datadog-agent'

      operation:
        description: 'Operation to perform (e.g., start, stop, restart, status)'
        required: true
        default: status
        type: choice
        options:
          - status
          - stop
          - start
          - restart

      host:
        description: 'Provide the hostname or IP'
        required: true

jobs:
  control-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run systemctl command on server
        env:
          SERVICE: ${{ github.event.inputs.service }}
          OPERATION: ${{ github.event.inputs.operation }}
          SERVER: ${{ github.event.inputs.host }}
          USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Running: sudo systemctl $OPERATION $SERVICE on $SERVER"
          ssh -o StrictHostKeyChecking=no $USER@$SERVER "sudo systemctl $OPERATION $SERVICE"
